| 2016-11-13 19:27:11 | object_manager.py | line: 96 | ERROR | get_object error-- [Errno 2] No such file or directory: 'D:\\MyCodes\\GitRepos\\OssAutoSync\\testDirect\\测试test\\\\'
| 2016-11-13 19:27:11 | object_manager.py | line: 96 | ERROR | get_object error-- [Errno 2] No such file or directory: 'D:\\MyCodes\\GitRepos\\OssAutoSync\\testDirect\\测试test\\新建文件夹 (2)\\\\'
| 2016-11-13 19:27:11 | object_manager.py | line: 96 | ERROR | get_object error-- [Errno 2] No such file or directory: 'D:\\MyCodes\\GitRepos\\OssAutoSync\\testDirect\\测试test\\新建文件夹\\\\'
| 2016-11-13 19:33:59 | object_manager.py | line: 77 | ERROR | put_object error-- [Errno 2] No such file or directory: 'D:\\MyCodes\\GitRepos\\OssAutoSync\\testDirect\\测试est'
| 2016-11-13 19:33:59 | object_manager.py | line: 77 | ERROR | put_object error-- [Errno 2] No such file or directory: 'D:\\MyCodes\\GitRepos\\OssAutoSync\\testDirect\\测试est'
