| 2016-11-16 17:51:23 | object_manager.py | line: 78 | ERROR | put_object error | D:\My Codes\MyRepo\OssAutoSync\testDirect\新建文本文档 (4).txt | {'status': 407, 'details': {}}
